name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
      - name: Run CI
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf
          deno task ci
